image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - staging

build:
  stage: build
  script:
    - npm install @angular/cli
    - ./node_modules/.bin/ng build --prod --build-optimizer
  artifacts:
    expire_in: 1 week
    paths:
      - dist/*
  only:
    - staging

deploy:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase use --add purse-diverse --token $FIREBASE_TOKEN staging
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - staging