image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - staging

build:
  stage: build
  script:
    - npm install @angular/cli
    - ./node_modules/.bin/ng build --prod --build-optimizer
  only:
    - staging

deploy:
  stage: deploy
  only:
    - staging 
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - staging